language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

install:
  - sudo apt-get update
  - sudo apt-get install libc6-i386
  - (git clone git://github.com/frc-4931/2014 && mv 2014/sunspotfrcsdk ~)

script:
  - ant -Dsunspot.home="`echo ~`"/sunspotfrcsdk jar-app
